// app/layout.js
//import './globals.css'
//import { Inter } from 'next/font/google'

import "./styles/all.css"
import "./styles/blog.css"
import "./styles/common.css" 
import "./styles/contact.css"
import "./styles/index.css" 
import "./styles/singleBlog.css"


import Footer from "./components/footer"
import Header from "./components/header"

//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
